### ISSUE TITLE
Add Ubuntu?

### ISSUE THREAD

**Issue by JarnoXYZ** [nelsonjchen/reverse-rdp-windows-github-actions#14]
Hi!

GitHub also works on ''ubuntu-latest''.

It does not have to be an RDP as you would have to install a bunch of packages.
I only need Terminal Access anyway.
Is that easy to make?

**Comment by nelsonjchen** [comment]
Pointless I think. See https://github.com/nelsonjchen/reverse-rdp-windows-github-actions#similar-projects and the tunshell entry. That thing makes it super easy for ubuntu-latest.

This repo exists because it isn't trivial to introspect Windows runners.

Now I did notice some and quite a lot of people trying to use this kind of stuff as some sort of quasi-workstation VPS or something which may or may not go against the GitHub TOS but anyway if you're in that camp, you're better off with https://github.com/features/codespaces.
